spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jackson:
    default-property-inclusion: NON_NULL
cub:
  currency:
    service:
      host: https://api.coindesk.com