CREATE TABLE Currency (
    ENG_CURRENCY VARCHAR(255) NOT NULL PRIMARY KEY,
    CHI_CURRENCY VARCHAR(255) NOT NULL,
    SYMBOL VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    RATE FLOAT NOT NULL,
    UPDATE_TIME DATETIME NOT NULL
);